-- Seed inicial do catálogo Colares Dias Semijoias
-- Observação: o PDF contém 84 itens precificados + 3 imagens editoriais (importadas como indisponíveis).

INSERT INTO public.products
(name, description, price, image_url, image_gallery, is_available, category, stock_quantity, condition)
VALUES
('Anel losango', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 51.00, '/catalogo/produtos/p02-i01.jpg', '["/catalogo/produtos/p02-i01.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Anel gota', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 59.00, '/catalogo/produtos/p02-i02.jpg', '["/catalogo/produtos/p02-i02.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Anel quadrado', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 59.00, '/catalogo/produtos/p02-i03.jpg', '["/catalogo/produtos/p02-i03.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Anel gota cravejado', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 62.00, '/catalogo/produtos/p02-i04.jpg', '["/catalogo/produtos/p02-i04.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Anel aparador zircônia', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 59.00, '/catalogo/produtos/p02-i05.jpg', '["/catalogo/produtos/p02-i05.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Anel cravejado zircônia', 'Peça da coleção Anéis e Brincos da Colares Dias Semijoias.', 79.00, '/catalogo/produtos/p02-i06.jpg', '["/catalogo/produtos/p02-i06.jpg"]'::jsonb, true, 'Anéis e Brincos', 1, 'novo'),
('Editorial Anéis e Brincos I', 'Imagem editorial de referência do catálogo.', 0.00, '/catalogo/produtos/p02-i07.jpg', '["/catalogo/produtos/p02-i07.jpg"]'::jsonb, false, 'Anéis e Brincos', 0, 'novo'),
('Editorial Anéis e Brincos II', 'Imagem editorial de referência do catálogo.', 0.00, '/catalogo/produtos/p02-i08.jpg', '["/catalogo/produtos/p02-i08.jpg"]'::jsonb, false, 'Anéis e Brincos', 0, 'novo'),
('Editorial Anéis e Brincos III', 'Imagem editorial de referência do catálogo.', 0.00, '/catalogo/produtos/p02-i09.jpg', '["/catalogo/produtos/p02-i09.jpg"]'::jsonb, false, 'Anéis e Brincos', 0, 'novo'),
('Brinco gota vazado', 'Peça inspirada nas formas orgânicas da natureza.', 77.00, '/catalogo/produtos/p03-i01.jpg', '["/catalogo/produtos/p03-i01.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco coração matelado', 'Peça inspirada nas formas orgânicas da natureza.', 55.00, '/catalogo/produtos/p03-i02.jpg', '["/catalogo/produtos/p03-i02.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco forma livre', 'Peça inspirada nas formas orgânicas da natureza.', 77.00, '/catalogo/produtos/p03-i03.jpg', '["/catalogo/produtos/p03-i03.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco escultura dourada', 'Peça inspirada nas formas orgânicas da natureza.', 87.00, '/catalogo/produtos/p03-i04.jpg', '["/catalogo/produtos/p03-i04.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco solar gold', 'Peça inspirada nas formas orgânicas da natureza.', 87.00, '/catalogo/produtos/p03-i05.jpg', '["/catalogo/produtos/p03-i05.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco orgânico médio', 'Peça inspirada nas formas orgânicas da natureza.', 77.00, '/catalogo/produtos/p03-i06.jpg', '["/catalogo/produtos/p03-i06.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco arco flúido', 'Peça inspirada nas formas orgânicas da natureza.', 102.00, '/catalogo/produtos/p03-i07.jpg', '["/catalogo/produtos/p03-i07.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco cacho orgânico', 'Peça inspirada nas formas orgânicas da natureza.', 69.00, '/catalogo/produtos/p03-i08.jpg', '["/catalogo/produtos/p03-i08.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Brinco contorno wave', 'Peça inspirada nas formas orgânicas da natureza.', 67.00, '/catalogo/produtos/p03-i09.jpg', '["/catalogo/produtos/p03-i09.jpg"]'::jsonb, true, 'Brincos Orgânicos', 1, 'novo'),
('Argola ondulada', 'Argola com design elegante para compor diferentes estilos.', 102.00, '/catalogo/produtos/p04-i01.jpg', '["/catalogo/produtos/p04-i01.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola dupla quadrada', 'Argola com design elegante para compor diferentes estilos.', 92.00, '/catalogo/produtos/p04-i02.jpg', '["/catalogo/produtos/p04-i02.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola fosca', 'Argola com design elegante para compor diferentes estilos.', 67.00, '/catalogo/produtos/p04-i03.jpg', '["/catalogo/produtos/p04-i03.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola dupla', 'Argola com design elegante para compor diferentes estilos.', 77.00, '/catalogo/produtos/p04-i04.jpg', '["/catalogo/produtos/p04-i04.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola dupla coração', 'Argola com design elegante para compor diferentes estilos.', 102.00, '/catalogo/produtos/p04-i05.jpg', '["/catalogo/produtos/p04-i05.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola dupla redonda', 'Argola com design elegante para compor diferentes estilos.', 102.00, '/catalogo/produtos/p04-i06.jpg', '["/catalogo/produtos/p04-i06.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola pingente coração', 'Argola com design elegante para compor diferentes estilos.', 26.00, '/catalogo/produtos/p04-i07.jpg', '["/catalogo/produtos/p04-i07.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola listras', 'Argola com design elegante para compor diferentes estilos.', 54.00, '/catalogo/produtos/p04-i08.jpg', '["/catalogo/produtos/p04-i08.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Argola orgânica média', 'Argola com design elegante para compor diferentes estilos.', 80.00, '/catalogo/produtos/p04-i09.jpg', '["/catalogo/produtos/p04-i09.jpg"]'::jsonb, true, 'Argolas', 1, 'novo'),
('Brinco orgânico gota', 'Peça da coleção Ródio com brilho sofisticado.', 89.00, '/catalogo/produtos/p05-i01.jpg', '["/catalogo/produtos/p05-i01.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco orgânico água', 'Peça da coleção Ródio com brilho sofisticado.', 112.00, '/catalogo/produtos/p05-i02.jpg', '["/catalogo/produtos/p05-i02.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco argola pérola', 'Peça da coleção Ródio com brilho sofisticado.', 48.00, '/catalogo/produtos/p05-i03.jpg', '["/catalogo/produtos/p05-i03.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco coração ondulado', 'Peça da coleção Ródio com brilho sofisticado.', 64.99, '/catalogo/produtos/p05-i04.jpg', '["/catalogo/produtos/p05-i04.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco gota vazado ródio', 'Peça da coleção Ródio com brilho sofisticado.', 64.99, '/catalogo/produtos/p05-i05.jpg', '["/catalogo/produtos/p05-i05.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco coração gotas', 'Peça da coleção Ródio com brilho sofisticado.', 81.90, '/catalogo/produtos/p05-i06.jpg', '["/catalogo/produtos/p05-i06.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco flor slim Delicare', 'Peça da coleção Ródio com brilho sofisticado.', 30.00, '/catalogo/produtos/p05-i07.jpg', '["/catalogo/produtos/p05-i07.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco flor Delicare', 'Peça da coleção Ródio com brilho sofisticado.', 41.99, '/catalogo/produtos/p05-i08.jpg', '["/catalogo/produtos/p05-i08.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco flor verde Delicare', 'Peça da coleção Ródio com brilho sofisticado.', 32.80, '/catalogo/produtos/p05-i09.jpg', '["/catalogo/produtos/p05-i09.jpg"]'::jsonb, true, 'Coleção Ródio', 1, 'novo'),
('Brinco ponto luz', 'Novidade do catálogo Colares Dias Semijoias.', 45.00, '/catalogo/produtos/p06-i01.jpg', '["/catalogo/produtos/p06-i01.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Brinco zircônia flor', 'Novidade do catálogo Colares Dias Semijoias.', 52.00, '/catalogo/produtos/p06-i02.jpg', '["/catalogo/produtos/p06-i02.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Brinco gota zircônia', 'Novidade do catálogo Colares Dias Semijoias.', 54.00, '/catalogo/produtos/p06-i03.jpg', '["/catalogo/produtos/p06-i03.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Conjunto coração', 'Novidade do catálogo Colares Dias Semijoias.', 107.00, '/catalogo/produtos/p06-i04.jpg', '["/catalogo/produtos/p06-i04.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Colar filha coração', 'Novidade do catálogo Colares Dias Semijoias.', 84.00, '/catalogo/produtos/p06-i05.jpg', '["/catalogo/produtos/p06-i05.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Conjunto borboleta', 'Novidade do catálogo Colares Dias Semijoias.', 75.00, '/catalogo/produtos/p06-i06.jpg', '["/catalogo/produtos/p06-i06.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Pulseira Delicare flor', 'Novidade do catálogo Colares Dias Semijoias.', 82.00, '/catalogo/produtos/p06-i07.jpg', '["/catalogo/produtos/p06-i07.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Colar pérolas', 'Novidade do catálogo Colares Dias Semijoias.', 98.00, '/catalogo/produtos/p06-i08.jpg', '["/catalogo/produtos/p06-i08.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Colar cruz e coração', 'Novidade do catálogo Colares Dias Semijoias.', 90.00, '/catalogo/produtos/p06-i09.jpg', '["/catalogo/produtos/p06-i09.jpg"]'::jsonb, true, 'Novidades', 1, 'novo'),
('Brinco resinado esfera', 'Peça delicada da coleção Delicare.', 49.90, '/catalogo/produtos/p07-i01.jpg', '["/catalogo/produtos/p07-i01.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco Delicare duplo', 'Peça delicada da coleção Delicare.', 68.00, '/catalogo/produtos/p07-i02.jpg', '["/catalogo/produtos/p07-i02.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco resinado quadrado', 'Peça delicada da coleção Delicare.', 45.00, '/catalogo/produtos/p07-i03.jpg', '["/catalogo/produtos/p07-i03.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco Delicare flor', 'Peça delicada da coleção Delicare.', 49.90, '/catalogo/produtos/p07-i04.jpg', '["/catalogo/produtos/p07-i04.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Colar Delicare pingente', 'Peça delicada da coleção Delicare.', 79.90, '/catalogo/produtos/p07-i05.jpg', '["/catalogo/produtos/p07-i05.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco Delicare slim', 'Peça delicada da coleção Delicare.', 34.99, '/catalogo/produtos/p07-i06.jpg', '["/catalogo/produtos/p07-i06.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Pulseira Delicare slim', 'Peça delicada da coleção Delicare.', 91.99, '/catalogo/produtos/p07-i07.jpg', '["/catalogo/produtos/p07-i07.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco matelado coração', 'Peça delicada da coleção Delicare.', 51.80, '/catalogo/produtos/p07-i08.jpg', '["/catalogo/produtos/p07-i08.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Brinco gota pérola', 'Peça delicada da coleção Delicare.', 45.90, '/catalogo/produtos/p07-i09.jpg', '["/catalogo/produtos/p07-i09.jpg"]'::jsonb, true, 'Coleção Delicare', 1, 'novo'),
('Bracelete orgânico', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 92.00, '/catalogo/produtos/p08-i01.jpg', '["/catalogo/produtos/p08-i01.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Bracelete liso', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 102.00, '/catalogo/produtos/p08-i02.jpg', '["/catalogo/produtos/p08-i02.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira dupla esferas', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 52.00, '/catalogo/produtos/p08-i03.jpg', '["/catalogo/produtos/p08-i03.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira borboleta pérola', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 62.00, '/catalogo/produtos/p08-i04.jpg', '["/catalogo/produtos/p08-i04.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Bracelete pingente coração', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 102.00, '/catalogo/produtos/p08-i05.jpg', '["/catalogo/produtos/p08-i05.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira lisa', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 60.00, '/catalogo/produtos/p08-i06.jpg', '["/catalogo/produtos/p08-i06.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira zircônia', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 76.00, '/catalogo/produtos/p08-i07.jpg', '["/catalogo/produtos/p08-i07.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira dupla lisa', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 52.00, '/catalogo/produtos/p08-i08.jpg', '["/catalogo/produtos/p08-i08.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Pulseira coração pérola', 'Pulseira com acabamento premium da Colares Dias Semijoias.', 80.00, '/catalogo/produtos/p08-i09.jpg', '["/catalogo/produtos/p08-i09.jpg"]'::jsonb, true, 'Pulseiras', 1, 'novo'),
('Escapulário Nossa Senhora', 'Peça com simbologia de fé e proteção.', 152.90, '/catalogo/produtos/p09-i01.jpg', '["/catalogo/produtos/p09-i01.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Brinco Nossa Sra. Aparecida', 'Peça com simbologia de fé e proteção.', 32.99, '/catalogo/produtos/p09-i02.jpg', '["/catalogo/produtos/p09-i02.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Colar coração zircônia', 'Peça com simbologia de fé e proteção.', 92.00, '/catalogo/produtos/p09-i03.jpg', '["/catalogo/produtos/p09-i03.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Brinco Nossa Senhora', 'Peça com simbologia de fé e proteção.', 56.00, '/catalogo/produtos/p09-i04.jpg', '["/catalogo/produtos/p09-i04.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Escapulário Anjo da Guarda', 'Peça com simbologia de fé e proteção.', 82.90, '/catalogo/produtos/p09-i05.jpg', '["/catalogo/produtos/p09-i05.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Escapulário graça', 'Peça com simbologia de fé e proteção.', 170.00, '/catalogo/produtos/p09-i06.jpg', '["/catalogo/produtos/p09-i06.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Escapulário cruz', 'Peça com simbologia de fé e proteção.', 152.90, '/catalogo/produtos/p09-i07.jpg', '["/catalogo/produtos/p09-i07.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Colar nada me faltará', 'Peça com simbologia de fé e proteção.', 121.80, '/catalogo/produtos/p09-i08.jpg', '["/catalogo/produtos/p09-i08.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Colar medalha de São Bento', 'Peça com simbologia de fé e proteção.', 137.80, '/catalogo/produtos/p09-i09.jpg', '["/catalogo/produtos/p09-i09.jpg"]'::jsonb, true, 'Coleção Religiosa', 1, 'novo'),
('Conjunto Delicare branco', 'Conjunto/colar para destacar o look com elegância.', 244.80, '/catalogo/produtos/p10-i01.jpg', '["/catalogo/produtos/p10-i01.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto pérola orgânica', 'Conjunto/colar para destacar o look com elegância.', 180.99, '/catalogo/produtos/p10-i02.jpg', '["/catalogo/produtos/p10-i02.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto Delicare verde', 'Conjunto/colar para destacar o look com elegância.', 240.90, '/catalogo/produtos/p10-i03.jpg', '["/catalogo/produtos/p10-i03.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto zircônia', 'Conjunto/colar para destacar o look com elegância.', 333.99, '/catalogo/produtos/p10-i04.jpg', '["/catalogo/produtos/p10-i04.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto concha espiral', 'Conjunto/colar para destacar o look com elegância.', 239.90, '/catalogo/produtos/p10-i05.jpg', '["/catalogo/produtos/p10-i05.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto pirâmide', 'Conjunto/colar para destacar o look com elegância.', 256.90, '/catalogo/produtos/p10-i06.jpg', '["/catalogo/produtos/p10-i06.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Colar folha', 'Conjunto/colar para destacar o look com elegância.', 82.80, '/catalogo/produtos/p10-i07.jpg', '["/catalogo/produtos/p10-i07.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Colar orgânico', 'Conjunto/colar para destacar o look com elegância.', 115.80, '/catalogo/produtos/p10-i08.jpg', '["/catalogo/produtos/p10-i08.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Choker orgânica', 'Conjunto/colar para destacar o look com elegância.', 122.90, '/catalogo/produtos/p10-i09.jpg', '["/catalogo/produtos/p10-i09.jpg"]'::jsonb, true, 'Conjuntos e Colares', 1, 'novo'),
('Conjunto Velvet vinho', 'Peça da coleção Velvet com tons intensos e textura marcante.', 160.99, '/catalogo/produtos/p11-i01.jpg', '["/catalogo/produtos/p11-i01.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo'),
('Conjunto Velvet marrom', 'Peça da coleção Velvet com tons intensos e textura marcante.', 160.99, '/catalogo/produtos/p11-i02.jpg', '["/catalogo/produtos/p11-i02.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo'),
('Conjunto Velvet orgânico', 'Peça da coleção Velvet com tons intensos e textura marcante.', 150.99, '/catalogo/produtos/p11-i03.jpg', '["/catalogo/produtos/p11-i03.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo'),
('Conjunto duplo vinho', 'Peça da coleção Velvet com tons intensos e textura marcante.', 165.99, '/catalogo/produtos/p11-i04.jpg', '["/catalogo/produtos/p11-i04.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo'),
('Conjunto choker orgânico', 'Peça da coleção Velvet com tons intensos e textura marcante.', 327.99, '/catalogo/produtos/p11-i05.jpg', '["/catalogo/produtos/p11-i05.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo'),
('Conjunto duplo marrom', 'Peça da coleção Velvet com tons intensos e textura marcante.', 165.99, '/catalogo/produtos/p11-i06.jpg', '["/catalogo/produtos/p11-i06.jpg"]'::jsonb, true, 'Coleção Velvet', 1, 'novo');
